language: php
os: linux
dist: xenial

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - master

jobs:
  fast_finish: true
  allow_failures:
    - php: master

env:
  jobs:
    - DEPENDENCIES="highest"
    - DEPENDENCIES="lowest"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest --no-scripts --optimize-autoloader --classmap-authoritative"

install:
  - if [[ "$DEPENDENCIES" = 'highest' ]]; then composer update $DEFAULT_COMPOSER_FLAGS; fi
  - if [[ "$DEPENDENCIES" = 'lowest' ]]; then composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

before_script:
  - if php --ri xdebug >/dev/null; then phpenv config-rm xdebug.ini; fi

script:
  - composer cs-check
  - composer code-analyse
  - phpunit --configuration phpunit.xml

notifications:
  email: false
