# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: PHP

on:
  - push

jobs:
  build:

    strategy:
      matrix:
        operating-system:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'

        php-version:
          - '7.3'
          - '7.4'
          - '8.0'

        dependencies:
          - 'lowest'
          - 'highest'

        guzzle-version:
          - '6.*'
          - '7.*'

    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php-version }} Test on ${{ matrix.operating-system }} with Guzzle v${{ matrix.guzzle-version }} and ${{ matrix.dependencies }} dependencies

    steps:
      - name: Configure git to avoid issues with line endings
        if: matrix.operating-system == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Checkout project files
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2.1.5
        with:
          path: vendor
          key: php-${{ matrix.php-version }}-guzzle-${{ matrix.guzzle-version }}-dependencies-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}

      - name: Install lowest dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true' && matrix.dependencies == 'lowest'
        run: composer require "guzzlehttp/guzzle:${{ matrix.guzzle-version }}" --no-interaction --no-ansi --no-progress --no-scripts --optimize-autoloader --classmap-authoritative --update-with-all-dependencies --prefer-lowest

      - name: Install highest dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true' && matrix.dependencies == 'highest'
        run: composer require "guzzlehttp/guzzle:${{ matrix.guzzle-version }}" --no-interaction --no-ansi --no-progress --no-scripts --optimize-autoloader --classmap-authoritative --update-with-all-dependencies

      - name: Check Code Style
        run: composer cs-check

      - name: Clear static analysis cache
        run: composer code-analyse:clear-cache

      - name: Extract major version of Guzzle
        id: get-major-version
        uses: actions/github-script@v3
        env:
          VERSION: ${{ matrix.guzzle-version }}
        with:
          script: core.setOutput('version', process.env.VERSION.split('.')[0])

      - name: Run static analysis
        run: composer code-analyse:guzzle${{ steps.get-major-version.outputs.version }}

      - name: Run Unit tests
        run: composer test-unit:guzzle${{ steps.get-major-version.outputs.version }}
